# Generated by Django 5.2.6 on 2025-09-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_site', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('shelf', models.IntegerField(blank=True, null=True)),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('case', models.IntegerField(blank=True, null=True)),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_sites', to='location.locationsite')),
            ],
            options={
                'ordering': ['section'],
            },
        ),
    ]
