# Generated by Django 5.2.6 on 2025-09-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_locationsite_location_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
