# Generated by Django 5.2.6 on 2025-09-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='location_sub_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
