# Generated by Django 5.2.6 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_locationsite_location_sub_site'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('om', 'section', 'shelf', 'case', 'item_number'), name='unique_location'),
        ),
    ]
