# Generated by Django 5.2.6 on 2025-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_location_unique_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='type',
            field=models.CharField(blank=True, choices=[('internal', 'Interno'), ('external', 'Externo')], max_length=255, null=True),
        ),
    ]
