# Generated by Django 5.2.6 on 2025-09-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_locationsite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='type',
            field=models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo')], max_length=255),
        ),
    ]
