# Generated by Django 5.2.6 on 2025-09-07 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=255, unique=True)),
                ('pn', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.CharField(blank=True, max_length=255, null=True)),
                ('tec_pub', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalent_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalent_of', to='item.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equivalents', to='item.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'equivalent_item'), name='unique_item_equivalent'), models.CheckConstraint(condition=models.Q(('item', models.F('equivalent_item')), _negated=True), name='prevent_self_equivalence')],
            },
        ),
    ]
