# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_aircraft_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
    ]
