# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['numeral']},
        ),
    ]
