# Generated by Django 5.2.6 on 2025-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_alter_aircraft_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='numeral',
            field=models.CharField(),
        ),
    ]
