# Generated by Django 5.2.6 on 2025-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_alter_aircraft_numeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='tsn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
