# Generated by Django 5.2.6 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
