# Generated by Django 5.2.6 on 2025-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='kanban',
            field=models.CharField(choices=[('ENGINE', 'Motor'), ('CELL', 'Célula'), ('NOT', 'Não')], default='COMUM', max_length=10),
        ),
    ]
