# Generated by Django 5.2.6 on 2025-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_kanban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
