# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['location']},
        ),
    ]
