# Generated by Django 5.2.6 on 2025-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
