# Generated by Django 5.2.6 on 2025-09-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_locationsite_type'),
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='outflow',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_outflows', to='location.location'),
        ),
    ]
