# Generated by Django 5.2.6 on 2025-09-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0001_initial'),
        ('item', '0002_item_aircraft_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='inflow',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items_inflows', to='item.item'),
            preserve_default=False,
        ),
    ]
