# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0002_remove_inflow_inventory_item_inflow_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at']},
        ),
    ]
