# Generated by Django 5.2.6 on 2025-10-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0002_alter_aircraft_options'),
        ('inventory', '0005_alter_inventory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True, verbose_name='Número do Pedido')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Data do Pedido')),
                ('requester', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitante')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador')),
                ('order_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Pedido')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Atendimento')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(blank=True, max_length=100, null=True, verbose_name='MPN')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Item')),
                ('pn_alt1', models.CharField(blank=True, max_length=100, null=True, verbose_name='PN Alternativo 1')),
                ('pn_alt2', models.CharField(blank=True, max_length=100, null=True, verbose_name='PN Alternativo 2')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('dpe', models.CharField(blank=True, max_length=100, null=True)),
                ('eglog', models.CharField(blank=True, max_length=100, null=True)),
                ('log', models.CharField(blank=True, max_length=100, null=True)),
                ('nf_answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota Fiscal de Atendimento')),
                ('attended_date', models.DateField(blank=True, null=True, verbose_name='Data de Atendimento')),
                ('collected', models.BooleanField(default=False, verbose_name='Coletado')),
                ('gmm', models.CharField(blank=True, max_length=100, null=True)),
                ('bms', models.CharField(blank=True, max_length=100, null=True)),
                ('hb_destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destino HB')),
                ('contract_old', models.BooleanField(default=False, verbose_name='Contrato Anterior (013)?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('troubleshooting', models.TextField(blank=True, null=True, verbose_name='Ação de Troubleshooting')),
                ('failure_description', models.TextField(blank=True, null=True, verbose_name='Descrição da Falha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='aircraft.aircraft')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['-created_at'],
            },
        ),
    ]
