# Generated by Django 5.2.6 on 2025-10-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_item_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='mpn',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pn_alt1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pn_alt2',
        ),
    ]
