# Generated by Django 5.2.6 on 2025-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_item_name_remove_orderitem_mpn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service_type',
            field=models.CharField(blank=True, choices=[('RMS', 'RMS'), ('FSM', 'FSM')], max_length=100, null=True, verbose_name='Tipo de Atendimento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('RUSH', 'RUSH'), ('PROG', 'PROG'), ('AOG', 'AOG')], max_length=100, null=True, verbose_name='Tipo de Pedido'),
        ),
    ]
