# Generated by Django 5.2.6 on 2025-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_service_type_orderitem_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tsn_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TSN do Item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tso_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TSO do Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('RMS', 'RMS'), ('FSM', 'FSM')], max_length=100, null=True, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Aberto'), ('CLOSE', 'Finalizado')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_type',
            field=models.CharField(blank=True, choices=[('RUSH', 'RUSH'), ('PROG', 'PROG'), ('AOG', 'AOG')], max_length=100, null=True, verbose_name='Tipo de Atendimento'),
        ),
    ]
