# Generated by Django 5.2.6 on 2025-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_tsn_item_orderitem_tso_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(max_length=255, unique=True, verbose_name='Número do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requester',
            field=models.CharField(blank=True, choices=[('1BAVEX', '1º BAvEx'), ('BMS', 'B Mnt Sup Av Ex')], max_length=255, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Aberto - Não Atendido'), ('OPEN2', 'Aberto - Atendido Parcialmente'), ('CLOSE', 'Finalizado - Atendido'), ('CLOSE2', 'Finalizado - Não Atendido'), ('CANCEL', 'Cancelado')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
