# Generated by Django 5.2.6 on 2025-10-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_year_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(verbose_name='Número do Pedido'),
        ),
    ]
