# Generated by Django 5.2.6 on 2025-10-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operator',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT', 'Não enviado'), ('OPEN', 'Aberto - Não Atendido'), ('OPEN2', 'Aberto - Atendido Parcialmente'), ('CLOSE', 'Finalizado - Atendido'), ('CLOSE2', 'Finalizado - Não Atendido'), ('CANCEL', 'Cancelado')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
