# Generated by Django 5.2.6 on 2025-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_operator_orderitem_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Item'),
        ),
    ]
