# Generated by Django 5.2.6 on 2025-12-03 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_alter_aircraft_options'),
        ('order', '0009_orderitem_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='aircraft_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_aircraft_destination', to='aircraft.aircraft'),
        ),
    ]
