# Generated by Django 5.2.6 on 2025-12-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitem_aircraft_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('RMS', 'RMS'), ('FSM', 'FSM'), ('REQ', 'REQ')], max_length=100, null=True, verbose_name='Tipo de Pedido'),
        ),
    ]
