# Generated by Django 5.2.6 on 2025-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_supplied',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
