# Generated by Django 5.2.6 on 2025-12-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_quantity_supplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_supplied',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
