# Generated by Django 5.2.6 on 2025-12-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderitem_quantity_supplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sn_attended',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
