# Generated by Django 5.2.6 on 2025-12-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_sn_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expiration_date_attended',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do Atendimento'),
        ),
    ]
