# Generated by Django 5.2.6 on 2025-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orderitem_expiration_date_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações sobre o Item'),
        ),
    ]
