# Generated by Django 5.2.6 on 2025-12-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='log',
            field=models.BooleanField(default=False, verbose_name='Log Card'),
        ),
    ]
