# Generated by Django 5.2.6 on 2026-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_orderitem_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('RMS', 'RMS'), ('FSM', 'FSM'), ('REQ', 'REQ')], max_length=500, null=True, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requester',
            field=models.CharField(blank=True, choices=[('1BAVEX', '1º BAvEx'), ('BMS', 'B Mnt Sup Av Ex')], max_length=500, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('NOT', 'Não enviado'), ('OPEN', 'Aberto - Não Atendido'), ('OPEN2', 'Aberto - Atendido Parcialmente'), ('CLOSE', 'Finalizado - Atendido'), ('CLOSE2', 'Finalizado - Não Atendido'), ('CANCEL', 'Cancelado')], max_length=500, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dpe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='eglog',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='gmm',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hb_destination',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Destino HB'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='nf_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nota Fiscal de Atendimento'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='operator',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Operador Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_type',
            field=models.CharField(blank=True, choices=[('RUSH', 'RUSH'), ('PROG', 'PROG'), ('AOG', 'AOG')], max_length=500, null=True, verbose_name='Tipo de Atendimento'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sn_attended',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
