# Generated by Django 5.2.6 on 2026-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_order_type_alter_order_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='aircraft_tsn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
